
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Mon May 28 13:29:56 EDT 2012
//----------------------------------------------------

package net.jpm.jsproc.cup;

/** CUP generated class containing symbol constants. */
public class TokenConstants {
  /* terminals */
  public static final int GT = 53;
  public static final int TYPEOF = 29;
  public static final int RSHIFT_EQ = 69;
  public static final int PLUS_EQ = 63;
  public static final int GE = 54;
  public static final int BOOL_CONST = 35;
  public static final int SEMI = 76;
  public static final int COMMA = 75;
  public static final int CATCH = 15;
  public static final int RBRACE = 81;
  public static final int THROW = 17;
  public static final int RPAREN = 79;
  public static final int LT = 51;
  public static final int LBRACE = 80;
  public static final int STRING_CONST = 34;
  public static final int LPAREN = 78;
  public static final int EQQ = 48;
  public static final int MOD_EQ = 67;
  public static final int LSHIFT_EQ = 68;
  public static final int RSHIFT_ZERO = 62;
  public static final int FALSE = 27;
  public static final int NOT = 43;
  public static final int NUMBER_CONST = 32;
  public static final int NEQQ = 50;
  public static final int LE = 52;
  public static final int ERROR = 84;
  public static final int VAR = 4;
  public static final int BIN_AND = 57;
  public static final int RSHIFT_ZERO_EQ = 70;
  public static final int XOR_EQ = 73;
  public static final int BIN_XOR = 59;
  public static final int EQ = 47;
  public static final int MOD = 40;
  public static final int BIN_OR = 58;
  public static final int REGEXP_CONST = 33;
  public static final int TRUE = 26;
  public static final int PLUS = 36;
  public static final int WHILE = 21;
  public static final int DELETE = 13;
  public static final int ASSIGN = 46;
  public static final int CONDITIONAL = 55;
  public static final int SWITCH = 9;
  public static final int DO = 20;
  public static final int FOR = 18;
  public static final int VOID = 30;
  public static final int DIV = 39;
  public static final int DIV_EQ = 66;
  public static final int RETURN = 5;
  public static final int MULT = 38;
  public static final int ELSE = 8;
  public static final int TRY = 14;
  public static final int BREAK = 22;
  public static final int DOT = 74;
  public static final int UNDEFINED = 25;
  public static final int NULL = 24;
  public static final int EOF = 0;
  public static final int OR_EQ = 72;
  public static final int THIS = 6;
  public static final int DEFAULT = 11;
  public static final int MINUS_EQ = 64;
  public static final int BIN_NOT = 56;
  public static final int FUNCTION = 3;
  public static final int AND_EQ = 71;
  public static final int MINUS = 37;
  public static final int IN = 19;
  public static final int OR = 42;
  public static final int error = 1;
  public static final int FINALLY = 16;
  public static final int CONTINUE = 23;
  public static final int IF = 7;
  public static final int INSTANCEOF = 28;
  public static final int ID = 2;
  public static final int MINUSMINUS = 45;
  public static final int COLON = 77;
  public static final int MULT_EQ = 65;
  public static final int RBRACKET = 83;
  public static final int CASE = 10;
  public static final int PLUSPLUS = 44;
  public static final int NEW = 12;
  public static final int RSHIFT = 61;
  public static final int NEQ = 49;
  public static final int AND = 41;
  public static final int LBRACKET = 82;
  public static final int LSHIFT = 60;
  public static final int WITH = 31;
}

